console.log("Assalam o Alaikum Mr. Usman Welcome to type script")
var a:string="AOA Mr. Usman, would you like to learn anything about Islamic System ( Khilafah)";
console.log(a);
var b:string="USMAN";
var c:string="usman";
var d:string="Usman";
console.log(b);
console.log(c);
console.log(d);
console.log('The Prophet Muhammad P.B.U.H Said, "Hussain AS is with me and I am with the Hussain"');
var n1:number=2;
var n2:number=4;
var n3:number=8;
var n4:number=5;
var n5:number=9;
var n6:number=7;
var n7:number=11;
var n8:number=15;
var n9:number=6;
var n10:number=16;
var sum:number=n1+n2+n3+n4+n5+n6+n7+n8+n9+n10;
console.log("Sum of all numbers =",sum);
var sub:number=n1-n2-n3-n4-n5-n6-n7-n8-n9-n10;
console.log("Difference = ",sub);
var mul:number=n1*n2*n3*n4*n5*n6*n7*n8*n9*n10;
console.log("Multiplication of all numbers =",mul);
var div:number=n2/n10;
console.log("Division of 2 numbers =",div);
var allops=n2+n3-n6+n4*n8/n4;
console.log("Result of 4 operations =",allops);
