"use strict";
console.log("Assalam o Alaikum Mr. Usman Welcome to type script");
var a = "AOA Mr. Usman, would you like to learn anything about Islamic System ( Khilafah)";
console.log(a);
var b = "USMAN";
var c = "usman";
var d = "Usman";
console.log(b);
console.log(c);
console.log(d);
console.log('The Prophet Muhammad P.B.U.H Said, "Hussain AS is with me and I am with the Hussain"');
var n1 = 2;
var n2 = 4;
var n3 = 8;
var n4 = 5;
var n5 = 9;
var n6 = 7;
var n7 = 11;
var n8 = 15;
var n9 = 6;
var n10 = 16;
var sum = n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10;
console.log("Sum of all numbers =", sum);
var sub = n1 - n2 - n3 - n4 - n5 - n6 - n7 - n8 - n9 - n10;
console.log("Difference = ", sub);
var mul = n1 * n2 * n3 * n4 * n5 * n6 * n7 * n8 * n9 * n10;
console.log("Multiplication of all numbers =", mul);
var div = n2 / n10;
console.log("Division of 2 numbers =", div);
var allops = n2 + n3 - n6 + n4 * n8 / n4;
console.log("Result of 4 operations =", allops);
